### ISSUE TITLE
Updater Doesn't Work

### ISSUE THREAD

**Issue by vsnrytune** [Skinz3/League-of-Legends-Bot#27]
> Unable to install update. Error:
System.IO.DirectoryNotFoundException: Could not find a part of the path 'F:\LeagueBot\repo\League-Of-Legends-BOT-master\Binaries'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileSystemEnumerableIterator`1.CommonInit()
   at System.IO.FileSystemEnumerableIterator`1..ctor(String path, String originalUserPath, String searchPattern, SearchOption searchOption, SearchResultHandler`1 resultHandler, Boolean checkHost)
   at System.IO.Directory.GetFiles(String path)
   at LeagueBot.Updater.MainWindow.Install()
   at LeagueBot.Updater.MainWindow.WebClient_DownloadFileCompleted(Object sender, AsyncCompletedEventArgs e)

**Comment by Skinz3** [comment]
Try to launch it as administrator. Did you remove some folders in the launcher directory?
