### ISSUE TITLE
Unhandled Exception

### ISSUE THREAD

**Issue by osbale** [Skinz3/League-of-Legends-Bot#94]
When executing StartCoop

Error msg: 
Unhandled Exception: System.ComponentModel.Win32Exception: The system cannot find the file specified
   at System.Diagnostics.Process.StartWithShellExecuteEx(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
   at LeagueBot.LCU.ClientLCU.OpenClient()
   at LeagueBot.Api.ClientApi.openClient()
   at LeagueBot.StartCoop.Execute()
   at LeagueBot.Patterns.PatternsManager.Execute(String name)
   at LeagueBot.Program.HandleCommand()
   at LeagueBot.Program.Main(String[] args)

**Comment by rathodkanishk** [comment]
I have the same error, is there anything we can do to fix this? 
Please help.

**Comment by CodingAgent1337** [comment]
"The system cannot find the specific path" read the fucking error you skids

**Comment by osbale** [comment]
> "The system cannot find the specific path" read the fucking error you skids

What a great comment you loser. Tell us the solution instead of sucking balls, wanker.
